[build]
  publish = "dist"
  command = "npm run build"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[redirects]]
from = "https://www.specials.keyback.io/*"
to = "https://specials.keyback.io/:splat 301!"
status = 301


     